build:
  environment:
    node: v12.10.0
    selenium: true
    variables:
      NODE_ENV: 'test'

  dependencies:
    after:
      - yarn global add forever

  tests:
    before:
      - forever start -c 'yarn serve' ./
    override:
      - command: yarn test
    after:
      - forever stopall
