build:
  environment:
    node: v12.10.0
    selenium: true
    variables:
      NODE_ENV: 'test'

  tests:
    before:
      - command: yarn serve
        background: true
    override:
      - command: yarn test
