language: node_js

node_js:
  - 12

env:
  global:
    - NODE_ENV='test'

before_script:
  - wget https://chromedriver.storage.googleapis.com/78.0.3904.11/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/build/iFaxity/jsramverk
